## learn about numpy with chai aur code

In [1]:
import numpy as np

### creating array from list

In [2]:
arr_1d = np.array([1,2,3])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)


[1 2 3]
[[1 2 3]
 [4 5 6]]


### List vs numpy

In [3]:
py_list = [1,2,3]
print("python list multiplication",py_list * 2)


np_array = np.array([1,2,3])              ## element wise multiplication
print("numpy array multiplication",np_array * 2)



import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n list opeartion time: ",time.time() - start)


start = time.time()
### np_array = np.array([i for i in range(10000000)])
np_array = np.arange(10000000) * 2
print("\n numpy opeartion time: ",time.time() - start)

python list multiplication [1, 2, 3, 1, 2, 3]
numpy array multiplication [2 4 6]

 list opeartion time:  1.8637397289276123

 numpy opeartion time:  0.100799560546875


### Creating array from scratch

In [4]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)


ones = np.ones((2,3))
print("ones array: \n",ones)

full= np.full((3,4),5)
print("full array: \n",full)

random = np.random.random((3,3))
print("random array: \n",random)

sequence = np.arange(10,20,2)
print("sequence array: \n",sequence)

linspace = np.linspace(10,20,5)
print("linspace array: \n",linspace)

empty = np.empty((3,4))
print("empty array: \n",empty)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random array: 
 [[0.80622731 0.81771629 0.52469724]
 [0.64025596 0.68203785 0.34081628]
 [0.31774076 0.77968474 0.28074175]]
sequence array: 
 [10 12 14 16 18]
linspace array: 
 [10.  12.5 15.  17.5 20. ]
empty array: 
 [[6.64121187e-310 1.76181754e-316 1.01855798e-312 9.54898106e-313]
 [1.03977794e-312 1.01855798e-312 1.23075756e-312 1.08221785e-312]
 [1.01855798e-312 9.76118064e-313 1.08221785e-312 1.06099790e-312]]


### vector, Matrix and Tensor

In [5]:
vector = np.array([1,2,3])
print("vector: \n",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: \n",matrix)

tensor = np.array([[[1,2],[4,5]],[[7,8],[10,11]]])
print("tensor: \n",tensor)

vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


### Array Properties

In [6]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("shape: \n",arr.shape)
print("dimension: \n",arr.ndim)
print("size: \n",arr.size)
print("data type: \n",arr.dtype)

shape: 
 (2, 3)
dimension: 
 2
size: 
 6
data type: 
 int64


### Array Reshaping

In [13]:
arr=np.arange(12)
print("original array: ",arr)

reshaped = arr.reshape(3,4)
print("\n reshaped array: \n",reshaped)

flattened = reshaped.flatten()
print("\n flattened array: ",flattened)

# ravel(returns view,instead of copy)
raveled = reshaped.ravel()
print("\n raveled array: ",raveled)


# transpose
transposed = reshaped.T
print("\n transposed array: \n",transposed)

original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 reshaped array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 transposed array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
