### Numpy array operations

In [2]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])

print("basic slicing: ",arr[2:7])
print("with step: ",arr[1:8:2])
print("negative slicing: ",arr[-3])

basic slicing:  [3 4 5 6 7]
with step:  [2 4 6 8]
negative slicing:  8


In [4]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("specific element",arr_2d[1,2])
print("entire row",arr_2d[2])
print("entire column",arr_2d[:,2])

specific element 6
entire row [7 8 9]
entire column [3 6 9]


### Sorting

In [5]:
unsorted = np.array([3,2,5,7,1,9])
print("sorted array: ",np.sort(unsorted))

arr_2d_unsorted = np.array([[2,1],[3,1],[4,2]])
print("sorted 2d array of column: ",np.sort(arr_2d_unsorted,axis=0))
print("sorted 2d array of row: ",np.sort(arr_2d_unsorted,axis=1))

sorted array:  [1 2 3 5 7 9]
sorted 2d array of column:  [[2 1]
 [3 1]
 [4 2]]
sorted 2d array of row:  [[1 2]
 [1 3]
 [2 4]]


### Filter

In [6]:
numbers =  np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers [numbers % 2 == 0]
print("even numbers: ",even_number)

even numbers:  [ 2  4  6  8 10]


### Filter With Mask

In [7]:
mask = numbers > 5
print("numbers greater than 5",numbers[mask])

numbers greater than 5 [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [8]:
indices = [0,2,4]
print(numbers[indices])


where_result = np.where(numbers > 5)
print(where_result)
print("NP where",numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [9]:
condition_array = np.where(numbers > 5, numbers * 4, numbers)
print(condition_array)

[ 1  2  3  4  5 24 28 32 36 40]


### Adding and Removing data

In [10]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


### Array Compatibility

In [13]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])

print("compatibility shapes",a.shape==b.shape)

compatibility shapes True


In [16]:
original = np.array([[1,2],[3,4]])
new_row=np.array([[5,6]])

with_new_row=np.vstack((original,new_row))
print(with_new_row)


new_col=np.array([[1],[3]])
with_new_col=np.hstack((original,new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 1]
 [3 4 3]]


In [17]:
arr=np.array([1,2,3,4,5,6])
deleted = np.delete(arr,2)
print(deleted)

[1 2 4 5 6]
