## learn about numpy with chai aur code

In [2]:
import numpy as np

### creating array from list

In [ ]:
arr_1d = np.array([1,2,3])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)


[1 2 3]
[[1 2 3]
 [4 5 6]]


### List vs numpy

In [4]:
py_list = [1,2,3]
print("python list multiplication",py_list * 2)


np_array = np.array([1,2,3])              ## element wise multiplication
print("numpy array multiplication",np_array * 2)



import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n list opeartion time: ",time.time() - start)


start = time.time()
### np_array = np.array([i for i in range(10000000)])
np_array = np.arange(10000000) * 2
print("\n numpy opeartion time: ",time.time() - start)

python list multiplication [1, 2, 3, 1, 2, 3]
numpy array multiplication [2 4 6]

 list opeartion time:  1.2096245288848877

 numpy opeartion time:  0.08060002326965332


### Creating array from scratch

In [5]:
zeros = np.zeros((3,4))
print("zeros array: \n",zeros)


ones = np.ones((2,3))
print("ones array: \n",ones)

full= np.full((3,4),5)
print("full array: \n",full)

random = np.random.random((3,3))
print("random array: \n",random)

sequence = np.arange(10,20,2)
print("sequence array: \n",sequence)

linspace = np.linspace(10,20,5)
print("linspace array: \n",linspace)

empty = np.empty((3,4))
print("empty array: \n",empty)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
random array: 
 [[0.1690416  0.99276219 0.22750698]
 [0.99641079 0.67039221 0.364928  ]
 [0.59410149 0.54395861 0.75238467]]
sequence array: 
 [10 12 14 16 18]
linspace array: 
 [10.  12.5 15.  17.5 20. ]
empty array: 
 [[1.17931432e-311 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [8.01097888e-307 3.83779438e+175 6.69902465e+170 6.22782864e-038]
 [6.58045002e-038 5.00108666e+174 2.54658961e-052 4.11645143e+179]]


### vector, Matrix and Tensor

In [6]:
vector = np.array([1,2,3])
print("vector: \n",vector)

matrix = np.array([[1,2,3],[4,5,6]])
print("matrix: \n",matrix)

tensor = np.array([[[1,2],[4,5]],[[7,8],[10,11]]])
print("tensor: \n",tensor)

vector: 
 [1 2 3]
matrix: 
 [[1 2 3]
 [4 5 6]]
tensor: 
 [[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


### Array Properties

In [7]:
arr = np.array([[1,2,3],
                [4,5,6]])
print("shape: \n",arr.shape)
print("dimension: \n",arr.ndim)
print("size: \n",arr.size)
print("data type: \n",arr.dtype)

shape: 
 (2, 3)
dimension: 
 2
size: 
 6
data type: 
 int64


### Array Reshaping