## learn about numpy with chai aur code

In [2]:
import numpy as np

**creating array from list**

In [3]:
arr_1d = np.array([1,2,3])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)


[1 2 3]
[[1 2 3]
 [4 5 6]]


**List vs numpy**

In [7]:
py_list = [1,2,3]
print("python list multiplication",py_list * 2)


np_array = np.array([1,2,3])              ## element wise multiplication
print("numpy array multiplication",np_array * 2)



import time
start = time.time()
py_list = [i*2 for i in range(10000000)]
print("\n list opeartion time: ",time.time() - start)


start = time.time()
### np_array = np.array([i for i in range(10000000)])
np_array = np.arange(10000000) * 2
print("\n numpy opeartion time: ",time.time() - start)

python list multiplication [1, 2, 3, 1, 2, 3]
numpy array multiplication [2 4 6]

 list opeartion time:  0.6463978290557861

 numpy opeartion time:  0.031223297119140625
